<a href="https://colab.research.google.com/github/alokkumar1986/06-Oct-2026-Python-FullStack/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#array()
import numpy as np
x = np.array([1, 2, 3, 4])
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(4,)


In [3]:
#arange()

import numpy as np

x = np.arange(1, 100, 5)
print(x)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [4]:
#linspace()

import numpy as np
x = np.linspace(1, 10, 5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
#empty()

import numpy as np

x = np.empty(4)

print(x)

[4.41675837e-315 7.90505033e-323 4.41633376e-315 9.88131292e-324]


In [8]:
#zeros()
#ones()

import numpy as np

x= np.zeros((2,2))
print(x)

y = np.ones((2,2))
print(y)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [32]:
import numpy as np

x = y = np.array([
    [
        [1, 2, 3, 4],
        [2, 3, 4, 5]
    ],
    [
        [3, 4, 5, 6],
        [4, 5, 6, 7]
    ]
    ])

print(x[0:1, 1:, 3:])

print(x[1:, 0:1, 1:3])


[[[5]]]
[[[4 5]]]


In [42]:
import numpy as np

x = np.array([1, 4, 9, 3])
y = np.array([6, 5, 7, 2])

z = np.hstack((x, y))
print(z)

p = np.vstack((x, y))
print(p)

q = np.stack((x, y), axis=1)  #axis = 0 ,x, y (horizontal, then join with vstack())
                              #axis = 1, x, y (vertical and join with hstack())
print(q)

r = np.concatenate((x, y))
print(r)

[1 4 9 3 6 5 7 2]
[[1 4 9 3]
 [6 5 7 2]]
[[1 6]
 [4 5]
 [9 7]
 [3 2]]
[1 4 9 3 6 5 7 2]


In [52]:
import numpy as np

arr = np.arange(24).reshape(4, 6)

print(arr)

print(np.hsplit(arr, 6))




[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[ 0],
       [ 6],
       [12],
       [18]]), array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2],
       [ 8],
       [14],
       [20]]), array([[ 3],
       [ 9],
       [15],
       [21]]), array([[ 4],
       [10],
       [16],
       [22]]), array([[ 5],
       [11],
       [17],
       [23]])]


In [56]:
import numpy as np

arr = np.arange(24).reshape(4, 6)

print(arr)

print(np.vsplit(arr, 4))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23]])]


In [62]:
import numpy as np

arr = np.arange(24).reshape(4, 6)

print(arr)

print(np.split(arr, 6, axis=1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[array([[ 0],
       [ 6],
       [12],
       [18]]), array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2],
       [ 8],
       [14],
       [20]]), array([[ 3],
       [ 9],
       [15],
       [21]]), array([[ 4],
       [10],
       [16],
       [22]]), array([[ 5],
       [11],
       [17],
       [23]])]


In [65]:
import numpy as np

arr = np.arange(24).reshape(4, 6)

print(arr+1)

print(np.add(arr, 1))

print(arr-1)

print(np.subtract(arr, 1))

print(arr*2)

print(np.multiply(arr, 2))

print(arr/2)

print(np.divide(arr, 2))

print(arr%2)

print(np.mod(arr, 2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[-1  0  1  2  3  4]
 [ 5  6  7  8  9 10]
 [11 12 13 14 15 16]
 [17 18 19 20 21 22]]
[[-1  0  1  2  3  4]
 [ 5  6  7  8  9 10]
 [11 12 13 14 15 16]
 [17 18 19 20 21 22]]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]


In [66]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([2, 3, 4, 5])

print(np.add(x, y))

print(np.subtract(x, y))

print(np.multiply(x, y))

print(np.divide(x, y))

[3 5 7 9]
[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
